# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc30c02819b4fae37d8d589ba59de4e291275658cb633ac6ea5b12e19a09c6a97d79c019beada53639f419fdcd70e3f5f7b5f1216d158b0eb2c59fbf48ba14ed

test:
  secret_key_base: 04bf06b80cc24b6dc56c1f5938da88cfaae48b8d3102600ce247f2d3a9e401482b7d31f97add8512737b1bdea0f1060b88107ecd4119b2e0c16df6597b00f8e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
